### ISSUE TITLE
设置定时任务，周期性清理早的数据

### ISSUE THREAD

**Issue by outsrkem** [outsrkem/ats#3]
- 初步设置清理6个月以上的数据，按事件的事件的时间`etime`清理

**Comment by outsrkem** [comment]
清理周期可配置
```
  cron:
    cleanlog:
      time: "03 3 * * *"
      days: 10
```
